# Generated by Django 5.2.17 on 2026-08-29 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.JSONField(help_text='{name, lat, lng}')),
                ('pickup_location', models.JSONField()),
                ('dropoff_location', models.JSONField()),
                ('current_cycle_used', models.FloatField(default=0, help_text='On-duty hours already used in the 70hr/8day cycle')),
                ('start_time', models.DateTimeField(help_text='Trip start in home-terminal time')),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('truck_number', models.CharField(blank=True, max_length=120)),
                ('home_terminal', models.CharField(blank=True, max_length=200)),
                ('total_miles', models.FloatField(default=0)),
                ('total_duration_minutes', models.FloatField(default=0)),
                ('days', models.PositiveIntegerField(default=1)),
                ('plan', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
